// Generated by gencpp from file han2um_test/jointstateResponse.msg
// DO NOT EDIT!


#ifndef HAN2UM_TEST_MESSAGE_JOINTSTATERESPONSE_H
#define HAN2UM_TEST_MESSAGE_JOINTSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace han2um_test
{
template <class ContainerAllocator>
struct jointstateResponse_
{
  typedef jointstateResponse_<ContainerAllocator> Type;

  jointstateResponse_()
    : th0(0.0)
    , th1(0.0)
    , th2(0.0)
    , th3(0.0)  {
    }
  jointstateResponse_(const ContainerAllocator& _alloc)
    : th0(0.0)
    , th1(0.0)
    , th2(0.0)
    , th3(0.0)  {
  (void)_alloc;
    }



   typedef double _th0_type;
  _th0_type th0;

   typedef double _th1_type;
  _th1_type th1;

   typedef double _th2_type;
  _th2_type th2;

   typedef double _th3_type;
  _th3_type th3;





  typedef boost::shared_ptr< ::han2um_test::jointstateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::han2um_test::jointstateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct jointstateResponse_

typedef ::han2um_test::jointstateResponse_<std::allocator<void> > jointstateResponse;

typedef boost::shared_ptr< ::han2um_test::jointstateResponse > jointstateResponsePtr;
typedef boost::shared_ptr< ::han2um_test::jointstateResponse const> jointstateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::han2um_test::jointstateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::han2um_test::jointstateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::han2um_test::jointstateResponse_<ContainerAllocator1> & lhs, const ::han2um_test::jointstateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.th0 == rhs.th0 &&
    lhs.th1 == rhs.th1 &&
    lhs.th2 == rhs.th2 &&
    lhs.th3 == rhs.th3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::han2um_test::jointstateResponse_<ContainerAllocator1> & lhs, const ::han2um_test::jointstateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace han2um_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::han2um_test::jointstateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::han2um_test::jointstateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::han2um_test::jointstateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::han2um_test::jointstateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::han2um_test::jointstateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::han2um_test::jointstateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::han2um_test::jointstateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c258b2f1adbf36fda60db76d5101a7b9";
  }

  static const char* value(const ::han2um_test::jointstateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc258b2f1adbf36fdULL;
  static const uint64_t static_value2 = 0xa60db76d5101a7b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::han2um_test::jointstateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "han2um_test/jointstateResponse";
  }

  static const char* value(const ::han2um_test::jointstateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::han2um_test::jointstateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 th0\n"
"float64 th1\n"
"float64 th2\n"
"float64 th3\n"
"\n"
;
  }

  static const char* value(const ::han2um_test::jointstateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::han2um_test::jointstateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.th0);
      stream.next(m.th1);
      stream.next(m.th2);
      stream.next(m.th3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointstateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::han2um_test::jointstateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::han2um_test::jointstateResponse_<ContainerAllocator>& v)
  {
    s << indent << "th0: ";
    Printer<double>::stream(s, indent + "  ", v.th0);
    s << indent << "th1: ";
    Printer<double>::stream(s, indent + "  ", v.th1);
    s << indent << "th2: ";
    Printer<double>::stream(s, indent + "  ", v.th2);
    s << indent << "th3: ";
    Printer<double>::stream(s, indent + "  ", v.th3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAN2UM_TEST_MESSAGE_JOINTSTATERESPONSE_H
