// Generated by gencpp from file han2um_test/path_moveResponse.msg
// DO NOT EDIT!


#ifndef HAN2UM_TEST_MESSAGE_PATH_MOVERESPONSE_H
#define HAN2UM_TEST_MESSAGE_PATH_MOVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace han2um_test
{
template <class ContainerAllocator>
struct path_moveResponse_
{
  typedef path_moveResponse_<ContainerAllocator> Type;

  path_moveResponse_()
    : task(false)  {
    }
  path_moveResponse_(const ContainerAllocator& _alloc)
    : task(false)  {
  (void)_alloc;
    }



   typedef uint8_t _task_type;
  _task_type task;





  typedef boost::shared_ptr< ::han2um_test::path_moveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::han2um_test::path_moveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct path_moveResponse_

typedef ::han2um_test::path_moveResponse_<std::allocator<void> > path_moveResponse;

typedef boost::shared_ptr< ::han2um_test::path_moveResponse > path_moveResponsePtr;
typedef boost::shared_ptr< ::han2um_test::path_moveResponse const> path_moveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::han2um_test::path_moveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::han2um_test::path_moveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::han2um_test::path_moveResponse_<ContainerAllocator1> & lhs, const ::han2um_test::path_moveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.task == rhs.task;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::han2um_test::path_moveResponse_<ContainerAllocator1> & lhs, const ::han2um_test::path_moveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace han2um_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::han2um_test::path_moveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::han2um_test::path_moveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::han2um_test::path_moveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::han2um_test::path_moveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::han2um_test::path_moveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::han2um_test::path_moveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::han2um_test::path_moveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e0b2940b5e773889a2f9a1e4538c9dc";
  }

  static const char* value(const ::han2um_test::path_moveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e0b2940b5e77388ULL;
  static const uint64_t static_value2 = 0x9a2f9a1e4538c9dcULL;
};

template<class ContainerAllocator>
struct DataType< ::han2um_test::path_moveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "han2um_test/path_moveResponse";
  }

  static const char* value(const ::han2um_test::path_moveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::han2um_test::path_moveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool task\n"
"\n"
;
  }

  static const char* value(const ::han2um_test::path_moveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::han2um_test::path_moveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_moveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::han2um_test::path_moveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::han2um_test::path_moveResponse_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAN2UM_TEST_MESSAGE_PATH_MOVERESPONSE_H
