// Generated by gencpp from file han2um_test/path_move.msg
// DO NOT EDIT!


#ifndef HAN2UM_TEST_MESSAGE_PATH_MOVE_H
#define HAN2UM_TEST_MESSAGE_PATH_MOVE_H

#include <ros/service_traits.h>


#include <han2um_test/path_moveRequest.h>
#include <han2um_test/path_moveResponse.h>


namespace han2um_test
{

struct path_move
{

typedef path_moveRequest Request;
typedef path_moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path_move
} // namespace han2um_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::han2um_test::path_move > {
  static const char* value()
  {
    return "744c937c05cffa87d3ea129969217073";
  }

  static const char* value(const ::han2um_test::path_move&) { return value(); }
};

template<>
struct DataType< ::han2um_test::path_move > {
  static const char* value()
  {
    return "han2um_test/path_move";
  }

  static const char* value(const ::han2um_test::path_move&) { return value(); }
};


// service_traits::MD5Sum< ::han2um_test::path_moveRequest> should match
// service_traits::MD5Sum< ::han2um_test::path_move >
template<>
struct MD5Sum< ::han2um_test::path_moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::han2um_test::path_move >::value();
  }
  static const char* value(const ::han2um_test::path_moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::han2um_test::path_moveRequest> should match
// service_traits::DataType< ::han2um_test::path_move >
template<>
struct DataType< ::han2um_test::path_moveRequest>
{
  static const char* value()
  {
    return DataType< ::han2um_test::path_move >::value();
  }
  static const char* value(const ::han2um_test::path_moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::han2um_test::path_moveResponse> should match
// service_traits::MD5Sum< ::han2um_test::path_move >
template<>
struct MD5Sum< ::han2um_test::path_moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::han2um_test::path_move >::value();
  }
  static const char* value(const ::han2um_test::path_moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::han2um_test::path_moveResponse> should match
// service_traits::DataType< ::han2um_test::path_move >
template<>
struct DataType< ::han2um_test::path_moveResponse>
{
  static const char* value()
  {
    return DataType< ::han2um_test::path_move >::value();
  }
  static const char* value(const ::han2um_test::path_moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAN2UM_TEST_MESSAGE_PATH_MOVE_H
