// Generated by gencpp from file han2um_test/jointstate.msg
// DO NOT EDIT!


#ifndef HAN2UM_TEST_MESSAGE_JOINTSTATE_H
#define HAN2UM_TEST_MESSAGE_JOINTSTATE_H

#include <ros/service_traits.h>


#include <han2um_test/jointstateRequest.h>
#include <han2um_test/jointstateResponse.h>


namespace han2um_test
{

struct jointstate
{

typedef jointstateRequest Request;
typedef jointstateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct jointstate
} // namespace han2um_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::han2um_test::jointstate > {
  static const char* value()
  {
    return "50eae85153eb979d8c8f4d321262116c";
  }

  static const char* value(const ::han2um_test::jointstate&) { return value(); }
};

template<>
struct DataType< ::han2um_test::jointstate > {
  static const char* value()
  {
    return "han2um_test/jointstate";
  }

  static const char* value(const ::han2um_test::jointstate&) { return value(); }
};


// service_traits::MD5Sum< ::han2um_test::jointstateRequest> should match
// service_traits::MD5Sum< ::han2um_test::jointstate >
template<>
struct MD5Sum< ::han2um_test::jointstateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::han2um_test::jointstate >::value();
  }
  static const char* value(const ::han2um_test::jointstateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::han2um_test::jointstateRequest> should match
// service_traits::DataType< ::han2um_test::jointstate >
template<>
struct DataType< ::han2um_test::jointstateRequest>
{
  static const char* value()
  {
    return DataType< ::han2um_test::jointstate >::value();
  }
  static const char* value(const ::han2um_test::jointstateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::han2um_test::jointstateResponse> should match
// service_traits::MD5Sum< ::han2um_test::jointstate >
template<>
struct MD5Sum< ::han2um_test::jointstateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::han2um_test::jointstate >::value();
  }
  static const char* value(const ::han2um_test::jointstateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::han2um_test::jointstateResponse> should match
// service_traits::DataType< ::han2um_test::jointstate >
template<>
struct DataType< ::han2um_test::jointstateResponse>
{
  static const char* value()
  {
    return DataType< ::han2um_test::jointstate >::value();
  }
  static const char* value(const ::han2um_test::jointstateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAN2UM_TEST_MESSAGE_JOINTSTATE_H
