
#goal definition
float64 fpos_x
float64 fpos_y
float64 fpos_z
---
#result definition
float64 fpos_x
float64 fpos_y
float64 fpos_z
bool task
---
#feedback
float64 fpos_x
float64 fpos_y
float64 fpos_z
